trigger:
  branches:
    include:
    - '*'
variables:
  system_accesstoken: $(System.AccessToken)

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true    #Allow scripts to access the system token
  clean: true 

- task: Bash@3
  name: SyncRepo
  inputs:
    targetType: 'inline'
    script: |
      git config --global user.email "ryan@gatesryan.com"
      git config --global user.name "gatesry"
      git checkout main
      git push https://$(System.AccessToken)@dev.azure.com/DK-IT-Portal/CISA-Scuba/_git/CISA-Scuba